// Temporary local development configuration
// For production builds, this file will be generated by scripts/generate_app_config.dart

class AppConfig {
  // Supabase Configuration
  static const String supabaseUrl = 'https://thsitslpyddlctxsywki.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoc2l0c2xweWRkbGN0eHN5d2tpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NzEzOTQsImV4cCI6MjA2OTA0NzM5NH0.c1DkvnqD6Llv9zgu-3SGcDyC-KctAwb0DhYWMqoYcpE';
  
  // Google Sign-In Configuration
  static const String googleWebClientId = '1011903996076-pvsnufkfdvpdmgv20nh27v7l3cfo4j8f.apps.googleusercontent.com';
  static const String googleIosClientId = '1011903996076-gjhg7cebfk1235102id7700u79ptdql2.apps.googleusercontent.com';
  
  // Local development - no dotenv needed
  static Future<void> initialize() async {
    // No-op for local static config
  }
  
  static String get environment => 'development';
  static bool get isProduction => false;
  static bool get isDevelopment => true;
}